name: Watermark Remover Setup pip

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-watermark-remover:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev zlib1g-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Watermark Removal Script
        run: |
          iopaint download --model lama
          python remwm.py

      # Step 7: Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automated changes after setup"
          git pull --rebase origin main || Write-Host "No changes to pull"
          git push origin main
